AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7.1
  NewCops: disable

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/*'
